import { Jost } from "next/font/google";

import "./globals.css";

const jost = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "Coffee Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jost}  antialiased capitalize`}
      >
        {children}
      </body>
    </html>
  );
}
