import { Jost } from "next/font/google";

import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/ui/Header";

const jost = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "Coffee Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (  
    <html lang="en">
      <body
        className={`${jost}  antialiased capitalize`}
      >
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
